### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by muztaba40** [amirfaraji/LowDoseCTPytorch#1]
when I tried to run the code from src file. it says error. Error massage is here:
Traceback (most recent call last):
  File "/media/muztaba-ahbab/Others Stuff/Study/HIWI/Mathematics/LowDoseCTPytorch-master/LowDoseCTPytorch-master/src/train.py", line 8, in <module>
    from client.ModelClient import ReconstructionModelClient
  File "/media/muztaba-ahbab/Others Stuff/Study/HIWI/Mathematics/LowDoseCTPytorch-master/LowDoseCTPytorch-master/src/client/ModelClient.py", line 10, in <module>
    from utils.CustomBar import CustomBar, Bar
  File "/media/muztaba-ahbab/Others Stuff/Study/HIWI/Mathematics/LowDoseCTPytorch-master/LowDoseCTPytorch-master/src/utils/CustomBar.py", line 1, in <module>
    from progress.bar import Bar
ModuleNotFoundError: No module named 'progress'

So can you tell me where is this progress file? I am tried but unable to find the file progress.bar.

**Comment by amirfaraji** [comment]
Hi, 

The library is: https://pypi.org/project/progress/
It should be in the requirements.txt file, so pip install should help resolve that.

**Comment by muztaba40** [comment]
Thank you for your feedback. I tried it worked. 

But after that a new error occurred. As I do not have 8 GB of GTx 2070Super instead I use GTx 1050Ti with 4GB. I used the batch size of 2 and then this appeared:
RuntimeError: stack expects each tensor to be equal size, but got [1, 1000, 513] at entry 0 and [1, 513, 1000] at entry 1

Can you tell me how to solve this issue?

**Comment by listar0810** [comment]
> Thank you for your feedback. I tried it worked.
> 
> But after that a new error occurred. As I do not have 8 GB of GTx 2070Super instead I use GTx 1050Ti with 4GB. I used the batch size of 2 and then this appeared: RuntimeError: stack expects each tensor to be equal size, but got [1, 1000, 513] at entry 0 and [1, 513, 1000] at entry 1
> 
> Can you tell me how to solve this issue?

I also have the problem, have u solved it? Thx!
