### ISSUE TITLE
TypeError: iradon() got an unexpected keyword argument 'filter'

### ISSUE THREAD

**Issue by Leoninetang** [amirfaraji/LowDoseCTPytorch#3]
when I tried to run the file train.py from src file. it says error. Error massage is here:
Traceback (most recent call last):
  File "D:\LowDoseCTPytorch-master\LowDoseCTPytorch-master\src\train.py", line 126, in <module>
    train()
  File "D:\LowDoseCTPytorch-master\LowDoseCTPytorch-master\src\train.py", line 95, in train
    validation = LowDoseCTDataset(
  File "D:\LowDoseCTPytorch-master\LowDoseCTPytorch-master\src\utils\DataHandler.py", line 45, in __init__
    self.__shape = self.__getitem__(0)['gt'].shape
  File "D:\LowDoseCTPytorch-master\LowDoseCTPytorch-master\src\utils\DataHandler.py", line 60, in __getitem__
    observation_data = self.fbp(self.read_hdf5(observation_filename)[data_idx])
  File "D:\anaconda\lib\site-packages\odl\operator\operator.py", line 686, in __call__
    out = self._call_out_of_place(x, **kwargs)
  File "D:\anaconda\lib\site-packages\odl\operator\operator.py", line 1364, in _call
    return self.left(self.right(x))
  File "D:\anaconda\lib\site-packages\odl\operator\operator.py", line 686, in __call__
    out = self._call_out_of_place(x, **kwargs)
  File "D:\anaconda\lib\site-packages\odl\tomo\operators\ray_trafo.py", line 314, in _call
    return self._call_real(x, out)
  File "D:\anaconda\lib\site-packages\odl\tomo\operators\ray_trafo.py", line 521, in _call_real
    return skimage_radon_back_projector(x_real, self.geometry,
  File "D:\anaconda\lib\site-packages\odl\tomo\backends\skimage_radon.py", line 144, in skimage_radon_back_projector
    backproj = iradon(skimage_sinogram.asarray().T, theta,
TypeError: iradon() got an unexpected keyword argument 'filter'

I am a newcomer to the pytorch application. Could you please tell me what is wrong with my operation. I am tried but unable to solve the problem. Thx.

**Comment by Ishak96** [comment]
Hello, try to install astra-toolbox : conda install -y -c astra-toolbox/label/dev astra-toolbox
then reinstall odl : pip install https://github.com/odlgroup/odl/archive/master.zip
